# Baseline B3_step_b.yml

model:
  num_classes: 
    person_activity: 9
    group_activity: 8

  num_classes_label:
    person_activity: ["Waiting", "Setting", "Digging", "Falling", "Spiking", "Blocking", "Jumping", "Moving", "Standing"]
    group_activity: ["r_set", "r_spike" , "r-pass", "r_winpoint", "l_winpoint", "l-pass", "l-spike", "l_set"]

training:
  batch_size: 32
  learning_rate: 0.0005 
  epochs: 15
  optimizer: "AdamW"
  weight_decay: 0.2

data:
  dataset_name: GroupActivityDataset
  data_dir: /kaggle/input/group-activity-recognition-volleyball
  annot_path: /kaggle/input/group-activity-recognition-volleyball/annot_all.pkl
  videos_path: /kaggle/input/group-activity-recognition-volleyball/videos

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]


experiment:
  name: "Baseline_B3_step_2"
  version: 1
  seed: 31
  output_dir: "outputs"
  description: "Bulid NN classifier to group activity"
