model:
  num_classes: 8 
  num_clases_label:  ["r_set", "r_spike" , "r-pass", "r_winpoint", "l_winpoint", "l-pass", "l-spike", "l_set"]

training:
  batch_size: 128
  learning_rate: 0.0001 # 1e-4
  epochs: 20
  optimizer: "AdamW"
  weight_decay: 0.01 

data:
  dataset_name: GroupActivityDataset
  data_dir: /kaggle/input/group-activity-recognition-volleyball
  annot_path: /kaggle/input/group-activity-recognition-volleyball/annot_all.pkl
  videos_path: /kaggle/input/group-activity-recognition-volleyball/videos

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

experiment:
  name: "Baseline_B1"
  version: 1
  seed: 31
  output_dir: "outputs"
  description: "Single-frame ResNet50 baseline 1 for group activity recognition"
