model:
  hidden_size: 128
  num_layers: 1 
  num_classes: 9
  num_classes_label: ["Waiting", "Setting", "Digging", "Falling", "Spiking", "Blocking", "Jumping", "Moving", "Standing"]

training:
  batch_size: 2
  learning_rate: 0.00001 
  epochs: 20
  optimizer: "AdamW"
  weight_decay: 0.1
  label_smoothing: 0.02 

data:
  dataset_name: GroupActivityDataset
  data_dir: /kaggle/input/group-activity-recognition-volleyball
  annot_path: /kaggle/input/group-activity-recognition-volleyball/annot_all.pkl
  videos_path: /kaggle/input/group-activity-recognition-volleyball/videos

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

experiment:
  name: "Baseline_B5_Step_A"
  version: 1
  seed: 31
  output_dir: "outputs"
  description: "Baseline5"